name: Docker Build and Push for Apache

on:
    push:
        branches: [ "main" ]
    schedule:
        - cron: "40 17 * * FRI"

jobs:
    build-apache:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build Apache Docker image
              run: |
                  docker build httpd/2.4 -t beninho/httpd:2.4
                  docker save -o httpd_2.4.tar beninho/httpd:2.4

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: httpd-2.4
                  path: httpd_2.4.tar

    push-apache:
        runs-on: ubuntu-latest
        needs: build-apache
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: httpd-2.4

            - name: Load Docker image
              run: docker load -i httpd_2.4.tar

            - name: Show Docker images
              run: docker images

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Push Apache Docker image
              run: |
                  docker push beninho/httpd:2.4
                  docker tag beninho/httpd:2.4 beninho/apache:2.4
                  docker push beninho/apache:2.4
