name: Docker Build and Push for PHP

on:
    push:
        branches: [ "main" ]
    schedule:
        - cron: "37 17 * * FRI"

jobs:
    build-php:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ["8.1", "8.2", "8.3", "8.3-pcov", "8.4", "8.4-pcov"]
                include:
                    -   version: "8.1"
                        folder: "php/8"
                        php_version: "8.1"
                    -   version: "8.2"
                        folder: "php/8"
                        php_version: "8.2"
                    -   version: "8.3"
                        folder: "php/8"
                        php_version: "8.3"
                    -   version: "8.3-pcov"
                        folder: "php/8-pcov"
                        php_version: "8.3"
                    -   version: "8.4"
                        folder: "php/8"
                        php_version: "8.4"
                    -   version: "8.4-pcov"
                        folder: "php/8-pcov"
                        php_version: "8.4"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: |
                  docker build ${{ matrix.folder }} --build-arg PHP_VERSION=${{ matrix.php_version }} -t beninho/php:${{ matrix.version }}
                  docker save -o php-${{ matrix.version }}.tar beninho/php:${{ matrix.version }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: php-${{ matrix.version }}
                  path: php-${{ matrix.version }}.tar

    push-php:
        runs-on: ubuntu-latest
        needs: build-php
        strategy:
            matrix:
                version: ["8.1", "8.2", "8.3", "8.3-pcov", "8.4", "8.4-pcov"]
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: php-${{ matrix.version }}

            - name: Load Docker image
              run: docker load -i php-${{ matrix.version }}.tar

            - name: Show Docker images
              run: docker images

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Push Docker image
              run: docker push beninho/php:${{ matrix.version }}

            - name: Push latest tag (if applicable)
              if: matrix.version == '8.4'
              run: |
                  docker tag beninho/php:8.4 beninho/php:latest
                  docker push beninho/php:latest
